AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Publish a new smugmug album.
Resources:
  smugmugcreatealbum:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: smugmug-actions
      Handler: smugmug_actions.handler.lambda_handler
      Runtime: python3.13
      InlineCode: def lambda_handler(event, context):-<
        print(event)
      Description: ''
      MemorySize: 128
      Timeout: 3
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: false
          AllowOrigins:
            - http://localhost:3000
            - https://www.oga.org.uk
            - https://oga.org.uk
          AllowHeaders:
            - content-type
          AllowMethods:
            - POST
            - GET
          MaxAge: 0
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: MAIL_*
        - SSMParameterReadPolicy:
            ParameterName: SMUGMUG/*
        - SQSSendMessagePolicy:
            QueueName: logging
        - S3ReadPolicy:
            BucketName: boatregister-upload
