AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Publish a new smugmug album.
Resources:
  smugmugcreatealbum:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: smugmug-create-album
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      InlineCode: def lambda_handler(event, context):-
        print(event)
      Description: ''
      MemorySize: 128
      Timeout: 3
      Policies:
        AWSSecretsManagerGetSecretValuePolicy:
          SecretArn: arn:aws:secretsmanager:eu-west-1:651845762820:secret:boatregister/smugmug-ai0FIR

